name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main  # Change to 'master' if that's your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Deploy to PythonAnywhere
      run: |
        # Deploy using webhook endpoint (more reliable than API console)
        curl -X POST "https://${{ secrets.PA_DOMAIN }}/deploy" \
        -H "Content-Type: application/json" \
        --fail --show-error
        
    - name: Notify deployment success
      if: success()
      run: echo "✅ Successfully deployed to PythonAnywhere!"
      
    - name: Notify deployment failure
      if: failure()
      run: echo "❌ Deployment failed. Check the logs above."
